# Generated by Django 2.1.4 on 2018-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_twitteruser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
